spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1/wechat_order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#    全局配置返回内容为notnull
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    password: rmt$redis1234
    port: 6379
    database: 15
